exclude: (^.idea/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        types: [ python ]
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        language: system
        types: [ python ]
        entry: autoflake
        require_serial: true
        args: [ '--in-place', '--remove-all-unused-imports', '--remove-unused-variables', '--recursive', '--remove-duplicate-keys']
      - id: pycln
        name: pycln
        language: system
        types: [ python ]
        entry: pycln
        require_serial: true
        args: [ '--all']
      - id: black
        name: black
        language: system
        types: [python]
        require_serial: true
        entry: black
      - id: mypy
        name: mypy
        language: system
        types: [ python ]
        entry: mypy
        require_serial: true
        args: [ --strict, --python-version=3.12, --show-error-codes, --allow-untyped-decorators ]
