exclude: ^.idea/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
        args: [--strict, --ignore-missing-imports, --python-version=3.6, --show-error-codes, --allow-untyped-decorators]
        additional_dependencies:
            - numpy>=1.19.2
            - pyspark>=2.4.0
            - logger
            - sparkautomapper>=0.1.27