version: '3.5'
services:
  dev:
    build:
      dockerfile: spark.Dockerfile
      context: .
    volumes:
    - ./:/sam_fhir/
    # ----- uncomment the below to get the code from local folders instead of pypi ----
#    - ../SparkAutoMapper/spark_auto_mapper:/opt/project/spark_auto_mapper
#    - ../SparkFhirSchemas/spark_fhir_schemas:/opt/project/spark_fhir_schemas
    container_name: sam_fhir_dev
    working_dir: /sam_fhir
