from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class Actionrelationshiptype(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class ActionrelationshiptypeValues:
    BeforeStart = Actionrelationshiptype("before-start")
    Before = Actionrelationshiptype("before")
    BeforeEnd = Actionrelationshiptype("before-end")
    ConcurrentWithStart = Actionrelationshiptype("concurrent-with-start")
    Concurrent = Actionrelationshiptype("concurrent")
    ConcurrentWithEnd = Actionrelationshiptype("concurrent-with-end")
    AfterStart = Actionrelationshiptype("after-start")
    After = Actionrelationshiptype("after")
    AfterEnd = Actionrelationshiptype("after-end")
