from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class AdditionalMaterialCodes(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class AdditionalMaterialCodesValues:
    XRay = AdditionalMaterialCodes("xray")
    Image = AdditionalMaterialCodes("image")
    Email = AdditionalMaterialCodes("email")
    Model = AdditionalMaterialCodes("model")
    Document = AdditionalMaterialCodes("document")
    Other = AdditionalMaterialCodes("other")
