from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class AdmitSourceCode(FhirValueSetBase):
    """
    AdmitSource
    """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class AdmitSourceCodeValues:
    TransferredFromOtherHospital = AdmitSourceCode("hosp-trans")
    FromAccident_emergencyDepartment = AdmitSourceCode("emd")
    FromOutpatientDepartment = AdmitSourceCode("outp")
    BornInHospital = AdmitSourceCode("born")
    GeneralPractitionerReferral = AdmitSourceCode("gp")
    MedicalPractitioner_physicianReferral = AdmitSourceCode("mp")
    FromNursingHome = AdmitSourceCode("nursing")
    FromPsychiatricHospital = AdmitSourceCode("psych")
    FromRehabilitationFacility = AdmitSourceCode("rehab")
    Other = AdmitSourceCode("other")
