from __future__ import annotations
from typing import Optional, Union, List, Any, TYPE_CHECKING

from pyspark.sql.types import StructType, DataType
from spark_auto_mapper_fhir.fhir_types.boolean import FhirBoolean
from spark_auto_mapper_fhir.fhir_types.date import FhirDate
from spark_auto_mapper_fhir.fhir_types.date_time import FhirDateTime
from spark_auto_mapper_fhir.fhir_types.list import FhirList
from spark_auto_mapper_fhir.fhir_types.integer import FhirInteger
from spark_auto_mapper_fhir.complex_types.meta import Meta
from spark_auto_mapper_fhir.extensions.extension_base import ExtensionBase
from spark_auto_mapper_fhir.fhir_types.id import FhirId

from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class CanonicalStatusCodesForFHIRResourcesCode(FhirValueSetBase):
    """
    Canonical Status Codes for FHIR Resources
    """
    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class CanonicalStatusCodesForFHIRResourcesCodeValues:
    Error = CanonicalStatusCodesForFHIRResourcesCode("error")
    Proposed = CanonicalStatusCodesForFHIRResourcesCode("proposed")
    Planned = CanonicalStatusCodesForFHIRResourcesCode("planned")
    Draft = CanonicalStatusCodesForFHIRResourcesCode("draft")
    Requested = CanonicalStatusCodesForFHIRResourcesCode("requested")
    Received = CanonicalStatusCodesForFHIRResourcesCode("received")
    Declined = CanonicalStatusCodesForFHIRResourcesCode("declined")
    Accepted = CanonicalStatusCodesForFHIRResourcesCode("accepted")
    Arrived = CanonicalStatusCodesForFHIRResourcesCode("arrived")
    Active = CanonicalStatusCodesForFHIRResourcesCode("active")
    Suspended = CanonicalStatusCodesForFHIRResourcesCode("suspended")
    Failed = CanonicalStatusCodesForFHIRResourcesCode("failed")
    Replaced = CanonicalStatusCodesForFHIRResourcesCode("replaced")
    Complete = CanonicalStatusCodesForFHIRResourcesCode("complete")
    Inactive = CanonicalStatusCodesForFHIRResourcesCode("inactive")
    Abandoned = CanonicalStatusCodesForFHIRResourcesCode("abandoned")
    Unknown = CanonicalStatusCodesForFHIRResourcesCode("unknown")
    Unconfirmed = CanonicalStatusCodesForFHIRResourcesCode("unconfirmed")
    Confirmed = CanonicalStatusCodesForFHIRResourcesCode("confirmed")
    Resolved = CanonicalStatusCodesForFHIRResourcesCode("resolved")
    Refuted = CanonicalStatusCodesForFHIRResourcesCode("refuted")
    Differential = CanonicalStatusCodesForFHIRResourcesCode("differential")
    Partial = CanonicalStatusCodesForFHIRResourcesCode("partial")
    Busy_unavailable = CanonicalStatusCodesForFHIRResourcesCode("busy-unavailable")
    Free = CanonicalStatusCodesForFHIRResourcesCode("free")
    On_target = CanonicalStatusCodesForFHIRResourcesCode("on-target")
    Ahead_of_target = CanonicalStatusCodesForFHIRResourcesCode("ahead-of-target")
    Behind_target = CanonicalStatusCodesForFHIRResourcesCode("behind-target")
    Not_ready = CanonicalStatusCodesForFHIRResourcesCode("not-ready")
    Transduc_discon = CanonicalStatusCodesForFHIRResourcesCode("transduc-discon")
    Hw_discon = CanonicalStatusCodesForFHIRResourcesCode("hw-discon")
