from __future__ import annotations
from typing import Optional, Union, List, Any, TYPE_CHECKING

from pyspark.sql.types import StructType, DataType
from spark_auto_mapper_fhir.fhir_types.boolean import FhirBoolean
from spark_auto_mapper_fhir.fhir_types.date import FhirDate
from spark_auto_mapper_fhir.fhir_types.date_time import FhirDateTime
from spark_auto_mapper_fhir.fhir_types.list import FhirList
from spark_auto_mapper_fhir.fhir_types.integer import FhirInteger
from spark_auto_mapper_fhir.complex_types.meta import Meta
from spark_auto_mapper_fhir.extensions.extension_base import ExtensionBase
from spark_auto_mapper_fhir.fhir_types.id import FhirId

from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class CommonLanguages_Written_Code(FhirValueSetBase):
    """
    Common Languages (Written)
    """
    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class CommonLanguages_Written_CodeValues:
    Arabic = CommonLanguages_Written_Code("ar")
    Bengali = CommonLanguages_Written_Code("bn")
    Czech = CommonLanguages_Written_Code("cs")
    Danish = CommonLanguages_Written_Code("da")
    German = CommonLanguages_Written_Code("de")
    Greek = CommonLanguages_Written_Code("el")
    English = CommonLanguages_Written_Code("en")
    Spanish = CommonLanguages_Written_Code("es")
    Finnish = CommonLanguages_Written_Code("fi")
    French = CommonLanguages_Written_Code("fr")
    Frysian = CommonLanguages_Written_Code("fy")
    Hindi = CommonLanguages_Written_Code("hi")
    Croatian = CommonLanguages_Written_Code("hr")
    Italian = CommonLanguages_Written_Code("it")
    Japanese = CommonLanguages_Written_Code("ja")
    Korean = CommonLanguages_Written_Code("ko")
    Dutch = CommonLanguages_Written_Code("nl")
    Norwegian = CommonLanguages_Written_Code("no")
    Punjabi = CommonLanguages_Written_Code("pa")
    Polish = CommonLanguages_Written_Code("pl")
    Portuguese = CommonLanguages_Written_Code("pt")
    Russian = CommonLanguages_Written_Code("ru")
    Serbian = CommonLanguages_Written_Code("sr")
    Swedish = CommonLanguages_Written_Code("sv")
    Telegu = CommonLanguages_Written_Code("te")
    Chinese = CommonLanguages_Written_Code("zh")
