from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class CommunicationNotDoneReason(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class CommunicationNotDoneReasonValues:
    Unknown = CommunicationNotDoneReason("unknown")
    SystemError = CommunicationNotDoneReason("system-error")
    InvalidPhoneNumber = CommunicationNotDoneReason("invalid-phone-number")
    RecipientUnavailable = CommunicationNotDoneReason("recipient-unavailable")
    FamilyObjection = CommunicationNotDoneReason("family-objection")
    PatientObjection = CommunicationNotDoneReason("patient-objection")
