from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class CompartmentTypeCode(FhirValueSetBase):
    """
    CompartmentType
    """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class CompartmentTypeCodeValues:
    Patient = CompartmentTypeCode("Patient")
    Encounter = CompartmentTypeCode("Encounter")
    RelatedPerson = CompartmentTypeCode("RelatedPerson")
    Practitioner = CompartmentTypeCode("Practitioner")
    Device = CompartmentTypeCode("Device")
