from __future__ import annotations


from spark_auto_mapper_fhir.value_sets.generic_type import GenericTypeCode
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class CoverageTypeAndSelf_PayCodesCode(GenericTypeCode):
    """
    CoverageTypeAndSelf-PayCodes
    From: http://hl7.org/fhir/ValueSet/coverage-type in valuesets.xml
        This value set includes Coverage Type codes.
    """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)
