from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class DeviceSafety(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class DeviceSafetyValues:
    MagneticResonanceConditional = DeviceSafety("C106046")
    MagneticResonanceSafe = DeviceSafety("C106045")
    MagneticResonanceUnsafe = DeviceSafety("C106047")
    LabelingDoesNotContainMRISafetyInformation = DeviceSafety("C113844")
    LabeledAsContainingNaturalRubberLatex = DeviceSafety("C101673")
    NotMadeWithNaturalRubberLatex = DeviceSafety("C106038")
