from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class ExampleMessageReasonCodesCode(FhirValueSetBase):
    """
    ExampleMessageReasonCodes
    """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class ExampleMessageReasonCodesCodeValues:
    Admit = ExampleMessageReasonCodesCode("admit")
    Discharge = ExampleMessageReasonCodesCode("discharge")
    Absent = ExampleMessageReasonCodesCode("absent")
    Returned = ExampleMessageReasonCodesCode("return")
    Moved = ExampleMessageReasonCodesCode("moved")
    Edit = ExampleMessageReasonCodesCode("edit")
