from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class ExampleDiagnosisTypeCodes(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class ExampleDiagnosisTypeCodesValues:
    AdmittingDiagnosis = ExampleDiagnosisTypeCodes("admitting")
    ClinicalDiagnosis = ExampleDiagnosisTypeCodes("clinical")
    DifferentialDiagnosis = ExampleDiagnosisTypeCodes("differential")
    DischargeDiagnosis = ExampleDiagnosisTypeCodes("discharge")
    LaboratoryDiagnosis = ExampleDiagnosisTypeCodes("laboratory")
    NursingDiagnosis = ExampleDiagnosisTypeCodes("nursing")
    PrenatalDiagnosis = ExampleDiagnosisTypeCodes("prenatal")
    PrincipalDiagnosis = ExampleDiagnosisTypeCodes("principal")
    RadiologyDiagnosis = ExampleDiagnosisTypeCodes("radiology")
    RemoteDiagnosis = ExampleDiagnosisTypeCodes("remote")
    RetrospectiveDiagnosis = ExampleDiagnosisTypeCodes("retrospective")
    SelfDiagnosis = ExampleDiagnosisTypeCodes("self")
