from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class Immunizationstatusreasoncodes(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class ImmunizationstatusreasoncodesValues:
    Actaccommodationreason = Immunizationstatusreasoncodes("_ActAccommodationReason")
    Actcoveragereason = Immunizationstatusreasoncodes("_ActCoverageReason")
    Actinformationmanagementreason = Immunizationstatusreasoncodes(
        "_ActInformationManagementReason"
    )
    Actinvalidreason = Immunizationstatusreasoncodes("_ActInvalidReason")
    Actinvoicecancelreason = Immunizationstatusreasoncodes("_ActInvoiceCancelReason")
    Actnoimmunizationreason = Immunizationstatusreasoncodes("_ActNoImmunizationReason")
    Actsupplyfulfillmentrefusalreason = Immunizationstatusreasoncodes(
        "_ActSupplyFulfillmentRefusalReason"
    )
    Clinicalresearcheventreason = Immunizationstatusreasoncodes(
        "_ClinicalResearchEventReason"
    )
    Clinicalresearchobservationreason = Immunizationstatusreasoncodes(
        "_ClinicalResearchObservationReason"
    )
    Combinedpharmacyordersuspendreasoncode = Immunizationstatusreasoncodes(
        "_CombinedPharmacyOrderSuspendReasonCode"
    )
    Controlactnullificationreasoncode = Immunizationstatusreasoncodes(
        "_ControlActNullificationReasonCode"
    )
    Controlactnullificationrefusalreasontype = Immunizationstatusreasoncodes(
        "_ControlActNullificationRefusalReasonType"
    )
    Controlactreason = Immunizationstatusreasoncodes("_ControlActReason")
    Genericupdatereasoncode = Immunizationstatusreasoncodes("_GenericUpdateReasonCode")
    PatientProfileQueryReason = Immunizationstatusreasoncodes(
        "_PatientProfileQueryReasonCode"
    )
    Pharmacysupplyrequestfulfillerrevisionrefusalreasoncode = (
        Immunizationstatusreasoncodes(
            "_PharmacySupplyRequestFulfillerRevisionRefusalReasonCode"
        )
    )
    Refusalreasoncode = Immunizationstatusreasoncodes("_RefusalReasonCode")
    Schedulingactreason = Immunizationstatusreasoncodes("_SchedulingActReason")
    Statusrevisionrefusalreasoncode = Immunizationstatusreasoncodes(
        "_StatusRevisionRefusalReasonCode"
    )
    Substanceadministrationpermissionrefusalreasoncode = Immunizationstatusreasoncodes(
        "_SubstanceAdministrationPermissionRefusalReasonCode"
    )
    Substanceadminsubstitutionnotallowedreason = Immunizationstatusreasoncodes(
        "_SubstanceAdminSubstitutionNotAllowedReason"
    )
    Substanceadminsubstitutionreason = Immunizationstatusreasoncodes(
        "_SubstanceAdminSubstitutionReason"
    )
    Transferactreason = Immunizationstatusreasoncodes("_TransferActReason")
    Actbillableservicereason = Immunizationstatusreasoncodes(
        "_ActBillableServiceReason"
    )
    Bonus = Immunizationstatusreasoncodes("BONUS")
    ChildrenOnly = Immunizationstatusreasoncodes("CHD")
    DependentsOnly = Immunizationstatusreasoncodes("DEP")
    EmployeeAndChildren = Immunizationstatusreasoncodes("ECH")
    Edu = Immunizationstatusreasoncodes("EDU")
    EmployeeOnly = Immunizationstatusreasoncodes("EMP")
    EmployeeAndSpouse = Immunizationstatusreasoncodes("ESP")
    Family = Immunizationstatusreasoncodes("FAM")
    Individual = Immunizationstatusreasoncodes("IND")
    Invoice = Immunizationstatusreasoncodes("INVOICE")
    Proa = Immunizationstatusreasoncodes("PROA")
    Recov = Immunizationstatusreasoncodes("RECOV")
    Retro = Immunizationstatusreasoncodes("RETRO")
    SpouseAndChildren = Immunizationstatusreasoncodes("SPC")
    SpouseOnly = Immunizationstatusreasoncodes("SPO")
    Tran = Immunizationstatusreasoncodes("TRAN")
    Immune = Immunizationstatusreasoncodes("IMMUNE")
    Medprec = Immunizationstatusreasoncodes("MEDPREC")
    Ostock = Immunizationstatusreasoncodes("OSTOCK")
    Patobj = Immunizationstatusreasoncodes("PATOBJ")
