from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class Immunizationrecommendationdatecriterioncodes(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class ImmunizationrecommendationdatecriterioncodesValues:
    _309815 = Immunizationrecommendationdatecriterioncodes("30981-5")
    _309807 = Immunizationrecommendationdatecriterioncodes("30980-7")
    _597773 = Immunizationrecommendationdatecriterioncodes("59777-3")
    _597781 = Immunizationrecommendationdatecriterioncodes("59778-1")
