from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class ImmunizationReasonCodesCode(FhirValueSetBase):
    """
    ImmunizationReasonCodes
    """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class ImmunizationReasonCodesCodeValues:
    _429060002 = ImmunizationReasonCodesCode("429060002")
    _281657000 = ImmunizationReasonCodesCode("281657000")
