from __future__ import annotations
from typing import Optional, Union, List, Any, TYPE_CHECKING

from pyspark.sql.types import StructType, DataType
from spark_auto_mapper_fhir.fhir_types.boolean import FhirBoolean
from spark_auto_mapper_fhir.fhir_types.date import FhirDate
from spark_auto_mapper_fhir.fhir_types.date_time import FhirDateTime
from spark_auto_mapper_fhir.fhir_types.list import FhirList
from spark_auto_mapper_fhir.fhir_types.integer import FhirInteger
from spark_auto_mapper_fhir.complex_types.meta import Meta
from spark_auto_mapper_fhir.extensions.extension_base import ExtensionBase
from spark_auto_mapper_fhir.fhir_types.id import FhirId
from spark_auto_mapper_fhir.fhir_types.uri import FhirUri

from spark_auto_mapper_fhir.value_sets.generic_type import GenericTypeCode
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class LocalRemoteControlState(GenericTypeCode):
    """
    v3.LocalRemoteControlState
    From: http://terminology.hl7.org/ValueSet/v3-LocalRemoteControlState in v3-codesystems.xml
        **** MISSING DEFINITIONS ****
    """
    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)

    """
    http://terminology.hl7.org/ValueSet/v3-LocalRemoteControlState
    """
    codeset: FhirUri = "http://terminology.hl7.org/ValueSet/v3-LocalRemoteControlState"
    """
    http://terminology.hl7.org/CodeSystem/v3-LocalRemoteControlState
    """
    codeset_2: FhirUri = "http://terminology.hl7.org/CodeSystem/v3-LocalRemoteControlState"


class LocalRemoteControlStateValues:
    """
    An equipment can either work autonomously ('Local' control state).
    From: http://terminology.hl7.org/CodeSystem/v3-LocalRemoteControlState in v3-codesystems.xml
    """
    Local = LocalRemoteControlState("L")
    """
    An equipment can be controlled by another system, e.g., LAS computer ('Remote'
    control state).
    From: http://terminology.hl7.org/CodeSystem/v3-LocalRemoteControlState in v3-codesystems.xml
    """
    Remote = LocalRemoteControlState("R")
