from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class MedicationKnowledgePackageTypeCodesCode(FhirValueSetBase):
    """
    medicationKnowledge Package Type Codes
    """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class MedicationKnowledgePackageTypeCodesCodeValues:
    Ampule = MedicationKnowledgePackageTypeCodesCode("amp")
    Bag = MedicationKnowledgePackageTypeCodesCode("bag")
    BlisterPack = MedicationKnowledgePackageTypeCodesCode("blstrpk")
    Bottle = MedicationKnowledgePackageTypeCodesCode("bot")
    Box = MedicationKnowledgePackageTypeCodesCode("box")
    Can = MedicationKnowledgePackageTypeCodesCode("can")
    Cartridge = MedicationKnowledgePackageTypeCodesCode("cart")
    Disk = MedicationKnowledgePackageTypeCodesCode("disk")
    Dosette = MedicationKnowledgePackageTypeCodesCode("doset")
    Jar = MedicationKnowledgePackageTypeCodesCode("jar")
    Jug = MedicationKnowledgePackageTypeCodesCode("jug")
    Minim = MedicationKnowledgePackageTypeCodesCode("minim")
    NebuleAmp = MedicationKnowledgePackageTypeCodesCode("nebamp")
    Ovule = MedicationKnowledgePackageTypeCodesCode("ovul")
    Pouch = MedicationKnowledgePackageTypeCodesCode("pch")
    Packet = MedicationKnowledgePackageTypeCodesCode("pkt")
    Sashet = MedicationKnowledgePackageTypeCodesCode("sash")
    Strip = MedicationKnowledgePackageTypeCodesCode("strip")
    Tin = MedicationKnowledgePackageTypeCodesCode("tin")
    Tub = MedicationKnowledgePackageTypeCodesCode("tub")
    Tube = MedicationKnowledgePackageTypeCodesCode("tube")
    Vial = MedicationKnowledgePackageTypeCodesCode("vial")
