from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class MedicationrequestStatusCode(FhirValueSetBase):
    """
    medicationrequest Status
    """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class MedicationrequestStatusCodeValues:
    Active = MedicationrequestStatusCode("active")
    OnHold = MedicationrequestStatusCode("on-hold")
    Cancelled = MedicationrequestStatusCode("cancelled")
    Completed = MedicationrequestStatusCode("completed")
    EnteredInError = MedicationrequestStatusCode("entered-in-error")
    Stopped = MedicationrequestStatusCode("stopped")
    Draft = MedicationrequestStatusCode("draft")
    Unknown = MedicationrequestStatusCode("unknown")
