from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class Messageheader_response_request(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class Messageheader_response_requestValues:
    Always = Messageheader_response_request("always")
    Error_rejectConditionsOnly = Messageheader_response_request("on-error")
    Never = Messageheader_response_request("never")
    SuccessfulCompletionOnly = Messageheader_response_request("on-success")
