from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class ObservationInterpretationCodesCode(FhirValueSetBase):
    """
    ObservationInterpretationCodes
    """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class ObservationInterpretationCodesCodeValues:
    Geneticobservationinterpretation = ObservationInterpretationCodesCode(
        "_GeneticObservationInterpretation"
    )
    Observationinterpretationchange = ObservationInterpretationCodesCode(
        "_ObservationInterpretationChange"
    )
    Observationinterpretationexceptions = ObservationInterpretationCodesCode(
        "_ObservationInterpretationExceptions"
    )
    Observationinterpretationnormality = ObservationInterpretationCodesCode(
        "_ObservationInterpretationNormality"
    )
    Observationinterpretationsusceptibility = ObservationInterpretationCodesCode(
        "_ObservationInterpretationSusceptibility"
    )
    OutsideThreshold = ObservationInterpretationCodesCode("EX")
    HoldForMedicalReview = ObservationInterpretationCodesCode("HM")
    Observationinterpretationdetection = ObservationInterpretationCodesCode(
        "ObservationInterpretationDetection"
    )
    Observationinterpretationexpectation = ObservationInterpretationCodesCode(
        "ObservationInterpretationExpectation"
    )
    InterpretationQualifiersInSeparateObxSegments = ObservationInterpretationCodesCode(
        "OBX"
    )
    Reactivityobservationinterpretation = ObservationInterpretationCodesCode(
        "ReactivityObservationInterpretation"
    )
