from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class ParticipationFunction(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class ParticipationFunctionValues:
    Authorizedparticipationfunction = ParticipationFunction(
        "_AuthorizedParticipationFunction"
    )
    Coverageparticipationfunction = ParticipationFunction(
        "_CoverageParticipationFunction"
    )
    AdmittingPhysician = ParticipationFunction("ADMPHYS")
    Anesthesist = ParticipationFunction("ANEST")
    AnesthesiaNurse = ParticipationFunction("ANRS")
    AssemblySoftware = ParticipationFunction("ASSEMBLER")
    AttendingPhysician = ParticipationFunction("ATTPHYS")
    ComposerSoftware = ParticipationFunction("COMPOSER")
    DischargingPhysician = ParticipationFunction("DISPHYS")
    FirstAssistantSurgeon = ParticipationFunction("FASST")
    Midwife = ParticipationFunction("MDWF")
    NurseAssistant = ParticipationFunction("NASST")
    PrimaryCarePhysician = ParticipationFunction("PCP")
    PrimarySurgeon = ParticipationFunction("PRISURG")
    Reviewer = ParticipationFunction("REVIEWER")
    RoundingPhysician = ParticipationFunction("RNDPHYS")
    SecondAssistantSurgeon = ParticipationFunction("SASST")
    ScrubNurse = ParticipationFunction("SNRS")
    ThirdAssistant = ParticipationFunction("TASST")
