from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class PatientMedicineChangeTypes(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class PatientMedicineChangeTypesValues:
    Unchanged = PatientMedicineChangeTypes("01")
    Changed = PatientMedicineChangeTypes("02")
    Cancelled = PatientMedicineChangeTypes("03")
    Prescribed = PatientMedicineChangeTypes("04")
    Ceased = PatientMedicineChangeTypes("05")
    Suspended = PatientMedicineChangeTypes("06")
