from __future__ import annotations
from typing import Optional, Union, List, Any, TYPE_CHECKING

from pyspark.sql.types import StructType, DataType
from spark_auto_mapper_fhir.fhir_types.boolean import FhirBoolean
from spark_auto_mapper_fhir.fhir_types.date import FhirDate
from spark_auto_mapper_fhir.fhir_types.date_time import FhirDateTime
from spark_auto_mapper_fhir.fhir_types.list import FhirList
from spark_auto_mapper_fhir.fhir_types.integer import FhirInteger
from spark_auto_mapper_fhir.complex_types.meta import Meta
from spark_auto_mapper_fhir.extensions.extension_base import ExtensionBase
from spark_auto_mapper_fhir.fhir_types.id import FhirId

from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class Postaladdressuse(FhirValueSetBase):
    """
    """
    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class PostaladdressuseValues:
    _generaladdressuse = Postaladdressuse("_GeneralAddressUse")
    _postaladdressuse = Postaladdressuse("_PostalAddressUse")
    _telecommunicationaddressuse = Postaladdressuse("_TelecommunicationAddressUse")
    BadAddress = Postaladdressuse("BAD")
    ConfidentialAddress = Postaladdressuse("CONF")
    PrimaryHome = Postaladdressuse("HP")
    VacationHome = Postaladdressuse("HV")
    Direct = Postaladdressuse("DIR")
    Public = Postaladdressuse("PUB")
    PhysicalVisitAddress = Postaladdressuse("PHYS")
    PostalAddress = Postaladdressuse("PST")
