from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class Procedurecategorycodessnomedct(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class ProcedurecategorycodessnomedctValues:
    _24642003 = Procedurecategorycodessnomedct("24642003")
    _409063005 = Procedurecategorycodessnomedct("409063005")
    _409073007 = Procedurecategorycodessnomedct("409073007")
    _387713003 = Procedurecategorycodessnomedct("387713003")
    _103693007 = Procedurecategorycodessnomedct("103693007")
    _46947000 = Procedurecategorycodessnomedct("46947000")
    _410606002 = Procedurecategorycodessnomedct("410606002")
