from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class Questionnaireresponsemode(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class QuestionnaireresponsemodeValues:
    ElectronicData = Questionnaireresponsemode("ELECTRONIC")
    PhysicalPresence = Questionnaireresponsemode("PHYSICAL")
    RemotePresence = Questionnaireresponsemode("REMOTE")
    Verbal = Questionnaireresponsemode("VERBAL")
    Written = Questionnaireresponsemode("WRITTEN")
    Electronic = Questionnaireresponsemode("ELECTRONIC")
    Verbal = Questionnaireresponsemode("VERBAL")
    Written = Questionnaireresponsemode("WRITTEN")
