from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class ResearchSubjectStatus(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class ResearchSubjectStatusValues:
    Candidate = ResearchSubjectStatus("candidate")
    Eligible = ResearchSubjectStatus("eligible")
    Follow_up = ResearchSubjectStatus("follow-up")
    Ineligible = ResearchSubjectStatus("ineligible")
    NotRegistered = ResearchSubjectStatus("not-registered")
    Off_study = ResearchSubjectStatus("off-study")
    On_study = ResearchSubjectStatus("on-study")
    On_study_intervention = ResearchSubjectStatus("on-study-intervention")
    On_study_observation = ResearchSubjectStatus("on-study-observation")
    PendingOn_study = ResearchSubjectStatus("pending-on-study")
    PotentialCandidate = ResearchSubjectStatus("potential-candidate")
    Screening = ResearchSubjectStatus("screening")
    Withdrawn = ResearchSubjectStatus("withdrawn")
