from __future__ import annotations

from spark_auto_mapper_fhir.fhir_types.uri import FhirUri

from spark_auto_mapper_fhir.value_sets.generic_type import GenericTypeCode
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class RoleClassAgent(GenericTypeCode):
    """
    v3.RoleClassAgent
    From: http://terminology.hl7.org/ValueSet/v3-RoleClassAgent in v3-codesystems.xml
         An entity (player) that acts or is authorized to act on behalf of another
    entity (scoper).
    """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)

    """
    http://terminology.hl7.org/ValueSet/v3-RoleClassAgent
    """
    codeset: FhirUri = "http://terminology.hl7.org/ValueSet/v3-RoleClassAgent"
