from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class SearchParamType(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class SearchParamTypeValues:
    Number = SearchParamType("number")
    Date_DateTime = SearchParamType("date")
    String = SearchParamType("string")
    Token = SearchParamType("token")
    Reference = SearchParamType("reference")
    Composite = SearchParamType("composite")
    Quantity = SearchParamType("quantity")
    URI = SearchParamType("uri")
    Special = SearchParamType("special")
