from __future__ import annotations
from typing import Optional, Union, List, Any, TYPE_CHECKING

from pyspark.sql.types import StructType, DataType
from spark_auto_mapper_fhir.fhir_types.boolean import FhirBoolean
from spark_auto_mapper_fhir.fhir_types.date import FhirDate
from spark_auto_mapper_fhir.fhir_types.date_time import FhirDateTime
from spark_auto_mapper_fhir.fhir_types.list import FhirList
from spark_auto_mapper_fhir.fhir_types.integer import FhirInteger
from spark_auto_mapper_fhir.complex_types.meta import Meta
from spark_auto_mapper_fhir.extensions.extension_base import ExtensionBase
from spark_auto_mapper_fhir.fhir_types.id import FhirId

from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class Servicecategory(FhirValueSetBase):
    """
    """
    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class ServicecategoryValues:
    Adoption = Servicecategory("1")
    AgedCare = Servicecategory("2")
    AlliedHealth = Servicecategory("34")
    AlternativecomplementaryTherapies = Servicecategory("3")
    ChildCarekindergarten = Servicecategory("4")
    ChildDevelopment = Servicecategory("5")
    ChildProtectionFamilyServices = Servicecategory("6")
    CommunityHealthCare = Servicecategory("7")
    Counselling = Servicecategory("8")
    CrisisLinegpahUseOnly = Servicecategory("36")
    DeathServices = Servicecategory("9")
    Dental = Servicecategory("10")
    DisabilitySupport = Servicecategory("11")
    Drugalcohol = Servicecategory("12")
    EducationLearning = Servicecategory("13")
    EmergencyDepartment = Servicecategory("14")
    Employment = Servicecategory("15")
    FinancialMaterialAid = Servicecategory("16")
    GeneralPractice = Servicecategory("17")
    Hospital = Servicecategory("35")
    Housinghomelessness = Servicecategory("18")
    Interpreting = Servicecategory("19")
    Justice = Servicecategory("20")
    Legal = Servicecategory("21")
    MentalHealth = Servicecategory("22")
    Ndia = Servicecategory("38")
    PhysicalActivityRecreation = Servicecategory("23")
    Regulation = Servicecategory("24")
    RespitecarerSupport = Servicecategory("25")
    SpecialistClinicalPathology = Servicecategory("26")
    SpecialistMedical = Servicecategory("27")
    SpecialistObstetricsGynecology = Servicecategory("28")
    SpecialistPaediatric = Servicecategory("29")
    SpecialistRadiologyimaging = Servicecategory("30")
    SpecialistSurgical = Servicecategory("31")
    SupportGroups = Servicecategory("32")
    TestMessagehsdAdmin = Servicecategory("37")
    Transport = Servicecategory("33")
