from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class Siblingrelationshipcodes(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class SiblingrelationshipcodesValues:
    Affiliationroletype = Siblingrelationshipcodes("_AffiliationRoleType")
    Assignedroletype = Siblingrelationshipcodes("_AssignedRoleType")
    Certifiedentitytype = Siblingrelationshipcodes("_CertifiedEntityType")
    Citizenroletype = Siblingrelationshipcodes("_CitizenRoleType")
    Contactroletype = Siblingrelationshipcodes("_ContactRoleType")
    Identifiedentitytype = Siblingrelationshipcodes("_IdentifiedEntityType")
    Livingsubjectproductionclass = Siblingrelationshipcodes(
        "_LivingSubjectProductionClass"
    )
    Medicationgeneralizationroletype = Siblingrelationshipcodes(
        "_MedicationGeneralizationRoleType"
    )
    Memberroletype = Siblingrelationshipcodes("_MemberRoleType")
    Personalrelationshiproletype = Siblingrelationshipcodes(
        "_PersonalRelationshipRoleType"
    )
    Policyorprogramcoverageroletype = Siblingrelationshipcodes(
        "_PolicyOrProgramCoverageRoleType"
    )
    Researchsubjectrolebasis = Siblingrelationshipcodes("_ResearchSubjectRoleBasis")
    Servicedeliverylocationroletype = Siblingrelationshipcodes(
        "_ServiceDeliveryLocationRoleType"
    )
    Specimenroletype = Siblingrelationshipcodes("_SpecimenRoleType")
    Claimant = Siblingrelationshipcodes("CLAIM")
    CommunityLaboratory = Siblingrelationshipcodes("communityLaboratory")
    Guarantor = Siblingrelationshipcodes("GT")
    HomeHealth = Siblingrelationshipcodes("homeHealth")
    Laboratory = Siblingrelationshipcodes("laboratory")
    Pathologist = Siblingrelationshipcodes("pathologist")
    PolicyHolder = Siblingrelationshipcodes("PH")
    Phlebotomist = Siblingrelationshipcodes("phlebotomist")
    ProgramEligible = Siblingrelationshipcodes("PROG")
    Patient = Siblingrelationshipcodes("PT")
    Self = Siblingrelationshipcodes("subject")
    ThirdParty = Siblingrelationshipcodes("thirdParty")
    Dep = Siblingrelationshipcodes("DEP")
    Dependent = Siblingrelationshipcodes("DEPEN")
    FamilyMember = Siblingrelationshipcodes("FM")
    Individual = Siblingrelationshipcodes("INDIV")
    NamedInsured = Siblingrelationshipcodes("NAMED")
    Psychcf = Siblingrelationshipcodes("PSYCHCF")
    Subscriber = Siblingrelationshipcodes("SUBSCR")
