from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class StatisticsCode(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class StatisticsCodeValues:
    Average = StatisticsCode("average")
    Maximum = StatisticsCode("maximum")
    Minimum = StatisticsCode("minimum")
    Count = StatisticsCode("count")
    TotalCount = StatisticsCode("total-count")
    Median = StatisticsCode("median")
    StandardDeviation = StatisticsCode("std-dev")
    Sum = StatisticsCode("sum")
    Variance = StatisticsCode("variance")
    _20thPercentile = StatisticsCode("20-percent")
    _80thPercentile = StatisticsCode("80-percent")
    LowerQuartile = StatisticsCode("4-lower")
    UpperQuartile = StatisticsCode("4-upper")
    QuartileDeviation = StatisticsCode("4-dev")
    _1stQuintile = StatisticsCode("5-1")
    _2ndQuintile = StatisticsCode("5-2")
    _3rdQuintile = StatisticsCode("5-3")
    _4thQuintile = StatisticsCode("5-4")
    Skew = StatisticsCode("skew")
    Kurtosis = StatisticsCode("kurtosis")
    Regression = StatisticsCode("regression")
