from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class Triggertype(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class TriggertypeValues:
    NamedEvent = Triggertype("named-event")
    Periodic = Triggertype("periodic")
    DataChanged = Triggertype("data-changed")
    DataAccessed = Triggertype("data-accessed")
    DataAccessEnded = Triggertype("data-access-ended")
