from __future__ import annotations


from spark_auto_mapper_fhir.base_types.FhirValueSetBase import FhirValueSetBase
from spark_auto_mapper.type_definitions.defined_types import AutoMapperTextInputType


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class UnknownContentCode(FhirValueSetBase):
    """ """

    def __init__(self, value: AutoMapperTextInputType):
        super().__init__(value=value)


class UnknownContentCodeValues:
    NeitherElementsOrExtensions = UnknownContentCode("no")
    UnknownExtensions = UnknownContentCode("extensions")
    UnknownElements = UnknownContentCode("elements")
    UnknownElementsAndExtensions = UnknownContentCode("both")
