from __future__ import annotations
from typing import Optional, Union, List, Any, TYPE_CHECKING

from pyspark.sql.types import StructType, DataType
from spark_auto_mapper_fhir.fhir_types.boolean import FhirBoolean
from spark_auto_mapper_fhir.fhir_types.date import FhirDate
from spark_auto_mapper_fhir.fhir_types.date_time import FhirDateTime
from spark_auto_mapper_fhir.fhir_types.list import FhirList
from spark_auto_mapper_fhir.fhir_types.integer import FhirInteger
from spark_auto_mapper_fhir.fhir_types.string import FhirString
from spark_auto_mapper_fhir.complex_types.meta import Meta
from spark_auto_mapper_fhir.extensions.extension_base import ExtensionBase
from spark_auto_mapper_fhir.fhir_types.id import FhirId

from spark_auto_mapper_fhir.base_types.fhir_backbone_element_base import (
    FhirBackboneElementBase,
)

if TYPE_CHECKING:
    # mode (DocumentMode)
    from spark_auto_mapper_fhir.complex_types.document_mode import DocumentMode
    # documentation (markdown)
    from spark_auto_mapper_fhir.complex_types.markdown import markdown
    # profile (canonical)
    from spark_auto_mapper_fhir.complex_types.canonical import canonical


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class CapabilityStatementDocument(FhirBackboneElementBase):
    """
    CapabilityStatement.Document
    """
    # noinspection PyPep8Naming
    def __init__(
        self,
        *,
        id_: FhirId,
        extension: Optional[FhirList[ExtensionBase]] = None,
        mode: DocumentMode ,
        documentation: Optional[markdown ] = None,
        profile: canonical ,
    ) -> None:
        """

        :param id_: id of resource
        :param extension: extensions
        :param mode: Mode of this document declaration - whether an application is a producer or
    consumer.
        :param documentation: A description of how the application supports or uses the specified document
    profile.  For example, when documents are created, what action is taken with
    consumed documents, etc.
        :param profile: A profile on the document Bundle that constrains which resources are present,
    and their contents.
        """
        super().__init__(
            id_=id_,
            extension=extension,
            mode=mode,
            documentation=documentation,
            profile=profile,
        )
