from __future__ import annotations
from typing import Optional, TYPE_CHECKING, Union

from spark_auto_mapper_fhir.fhir_types.boolean import FhirBoolean
from spark_auto_mapper_fhir.fhir_types.list import FhirList
from spark_auto_mapper_fhir.fhir_types.string import FhirString
from spark_auto_mapper_fhir.complex_types.meta import Meta
from spark_auto_mapper_fhir.extensions.extension_base import ExtensionBase
from spark_auto_mapper_fhir.fhir_types.id import FhirId

from spark_auto_mapper_fhir.base_types.fhir_backbone_element_base import (
    FhirBackboneElementBase,
)

if TYPE_CHECKING:
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept

    # Import for CodeableConcept for category
    from spark_auto_mapper_fhir.value_sets.benefitcategorycodes import (
        Benefitcategorycodes,
    )

    # End Import for CodeableConcept for category
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept

    # Import for CodeableConcept for productOrService
    from spark_auto_mapper_fhir.value_sets.usclscodes import Usclscodes

    # End Import for CodeableConcept for productOrService
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept

    # Import for CodeableConcept for modifier
    from spark_auto_mapper_fhir.value_sets.modifiertypecodes import Modifiertypecodes

    # End Import for CodeableConcept for modifier
    from spark_auto_mapper_fhir.complex_types.reference import Reference

    # Imports for References for provider
    from spark_auto_mapper_fhir.resources.practitioner import Practitioner
    from spark_auto_mapper_fhir.resources.practitioner_role import PractitionerRole
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept

    # Import for CodeableConcept for network
    from spark_auto_mapper_fhir.value_sets.networktypecodes import Networktypecodes

    # End Import for CodeableConcept for network
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept

    # Import for CodeableConcept for unit
    from spark_auto_mapper_fhir.value_sets.unittypecodes import Unittypecodes

    # End Import for CodeableConcept for unit
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept

    # Import for CodeableConcept for term
    from spark_auto_mapper_fhir.value_sets.benefittermcodes import Benefittermcodes

    # End Import for CodeableConcept for term
    from spark_auto_mapper_fhir.backbone_elements.coverage_eligibility_response_benefit import (
        CoverageEligibilityResponseBenefit,
    )
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept

    # Import for CodeableConcept for authorizationSupporting
    from spark_auto_mapper_fhir.value_sets.coverageeligibilityresponseauthsupportcodes import (
        Coverageeligibilityresponseauthsupportcodes,
    )

    # End Import for CodeableConcept for authorizationSupporting
    from spark_auto_mapper_fhir.complex_types.uri import uri


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class CoverageEligibilityResponseItem(FhirBackboneElementBase):
    """ """

    # noinspection PyPep8Naming
    def __init__(
        self,
        *,
        id_: FhirId,
        meta: Optional[Meta] = None,
        extension: Optional[FhirList[ExtensionBase]] = None,
        category: Optional[CodeableConcept[Benefitcategorycodes]] = None,
        productOrService: Optional[CodeableConcept[Usclscodes]] = None,
        modifier: Optional[FhirList[CodeableConcept[Modifiertypecodes]]] = None,
        provider: Optional[Reference[Union[Practitioner, PractitionerRole]]] = None,
        excluded: Optional[FhirBoolean] = None,
        name: Optional[FhirString] = None,
        description: Optional[FhirString] = None,
        network: Optional[CodeableConcept[Networktypecodes]] = None,
        unit: Optional[CodeableConcept[Unittypecodes]] = None,
        term: Optional[CodeableConcept[Benefittermcodes]] = None,
        benefit: Optional[FhirList[CoverageEligibilityResponseBenefit]] = None,
        authorizationRequired: Optional[FhirBoolean] = None,
        authorizationSupporting: Optional[
            FhirList[CodeableConcept[Coverageeligibilityresponseauthsupportcodes]]
        ] = None,
        authorizationUrl: Optional[uri] = None,
    ) -> None:
        """

            :param id_: id of resource
            :param meta: Meta
            :param extension: extensions
            :param category: Code to identify the general type of benefits under which products and
        services are provided.
            :param productOrService: This contains the product, service, drug or other billing code for the item.
            :param modifier: Item typification or modifiers codes to convey additional context for the
        product or service.
            :param provider: The practitioner who is eligible for the provision of the product or service.
            :param excluded: True if the indicated class of service is excluded from the plan, missing or
        False indicates the product or service is included in the coverage.
            :param name: A short name or tag for the benefit.
            :param description: A richer description of the benefit or services covered.
            :param network: Is a flag to indicate whether the benefits refer to in-network providers or
        out-of-network providers.
            :param unit: Indicates if the benefits apply to an individual or to the family.
            :param term: The term or period of the values such as 'maximum lifetime benefit' or
        'maximum annual visits'.
            :param benefit: Benefits used to date.
            :param authorizationRequired: A boolean flag indicating whether a preauthorization is required prior to
        actual service delivery.
            :param authorizationSupporting: Codes or comments regarding information or actions associated with the
        preauthorization.
            :param authorizationUrl: A web location for obtaining requirements or descriptive information regarding
        the preauthorization.
        """
        super().__init__(
            resourceType="CoverageEligibilityResponseItem",
            id_=id_,
            meta=meta,
            extension=extension,
            category=category,
            productOrService=productOrService,
            modifier=modifier,
            provider=provider,
            excluded=excluded,
            name=name,
            description=description,
            network=network,
            unit=unit,
            term=term,
            benefit=benefit,
            authorizationRequired=authorizationRequired,
            authorizationSupporting=authorizationSupporting,
            authorizationUrl=authorizationUrl,
        )
