from __future__ import annotations
from typing import Optional, TYPE_CHECKING

from spark_auto_mapper_fhir.fhir_types.list import FhirList
from spark_auto_mapper_fhir.complex_types.meta import Meta
from spark_auto_mapper_fhir.extensions.extension_base import ExtensionBase
from spark_auto_mapper_fhir.fhir_types.id import FhirId

from spark_auto_mapper_fhir.base_types.fhir_backbone_element_base import (
    FhirBackboneElementBase,
)

if TYPE_CHECKING:
    from spark_auto_mapper_fhir.complex_types.decimal import decimal
    from spark_auto_mapper_fhir.complex_types.decimal import decimal
    from spark_auto_mapper_fhir.complex_types.decimal import decimal


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class LocationPosition(FhirBackboneElementBase):
    """ """

    # noinspection PyPep8Naming
    def __init__(
        self,
        *,
        id_: FhirId,
        meta: Optional[Meta] = None,
        extension: Optional[FhirList[ExtensionBase]] = None,
        longitude: decimal,
        latitude: decimal,
        altitude: Optional[decimal] = None,
    ) -> None:
        """

            :param id_: id of resource
            :param meta: Meta
            :param extension: extensions
            :param longitude: Longitude. The value domain and the interpretation are the same as for the
        text of the longitude element in KML (see notes below).
            :param latitude: Latitude. The value domain and the interpretation are the same as for the text
        of the latitude element in KML (see notes below).
            :param altitude: Altitude. The value domain and the interpretation are the same as for the text
        of the altitude element in KML (see notes below).
        """
        super().__init__(
            resourceType="LocationPosition",
            id_=id_,
            meta=meta,
            extension=extension,
            longitude=longitude,
            latitude=latitude,
            altitude=altitude,
        )
