from __future__ import annotations
from typing import Optional, TYPE_CHECKING, Union

from spark_auto_mapper_fhir.fhir_types.list import FhirList
from spark_auto_mapper_fhir.fhir_types.string import FhirString

from spark_auto_mapper_fhir.base_types.fhir_backbone_element_base import (
    FhirBackboneElementBase,
)

if TYPE_CHECKING:
    pass
    # id_ (string)
    # extension (Extension)
    from spark_auto_mapper_fhir.extensions.extension import Extension

    # modifierExtension (Extension)
    # dosage (MedicationKnowledge.Dosage)
    from spark_auto_mapper_fhir.backbone_elements.medication_knowledge_dosage import (
        MedicationKnowledgeDosage,
    )

    # indicationCodeableConcept (CodeableConcept)
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept

    # End Import for References for indicationCodeableConcept
    # Import for CodeableConcept for indicationCodeableConcept
    from spark_auto_mapper_fhir.value_sets.generic_type import GenericTypeCode

    # End Import for CodeableConcept for indicationCodeableConcept
    # indicationReference (Reference)
    from spark_auto_mapper_fhir.complex_types.reference import Reference

    # Imports for References for indicationReference
    from spark_auto_mapper_fhir.resources.observation_definition import (
        ObservationDefinition,
    )

    # patientCharacteristics (MedicationKnowledge.PatientCharacteristics)
    from spark_auto_mapper_fhir.backbone_elements.medication_knowledge_patient_characteristics import (
        MedicationKnowledgePatientCharacteristics,
    )


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class MedicationKnowledgeAdministrationGuidelines(FhirBackboneElementBase):
    """
    MedicationKnowledge.AdministrationGuidelines
        Information about a medication that is used to support knowledge.
    """

    # noinspection PyPep8Naming
    def __init__(
        self,
        *,
        id_: Optional[FhirString] = None,
        extension: Optional[FhirList[Extension]] = None,
        modifierExtension: Optional[FhirList[Extension]] = None,
        dosage: Optional[FhirList[MedicationKnowledgeDosage]] = None,
        indicationCodeableConcept: Optional[CodeableConcept[GenericTypeCode]] = None,
        indicationReference: Optional[Reference[Union[ObservationDefinition]]] = None,
        patientCharacteristics: Optional[
            FhirList[MedicationKnowledgePatientCharacteristics]
        ] = None,
    ) -> None:
        """
            Information about a medication that is used to support knowledge.

            :param id_: None
            :param extension: May be used to represent additional information that is not part of the basic
        definition of the element. To make the use of extensions safe and manageable,
        there is a strict set of governance  applied to the definition and use of
        extensions. Though any implementer can define an extension, there is a set of
        requirements that SHALL be met as part of the definition of the extension.
            :param modifierExtension: May be used to represent additional information that is not part of the basic
        definition of the element and that modifies the understanding of the element
        in which it is contained and/or the understanding of the containing element's
        descendants. Usually modifier elements provide negation or qualification. To
        make the use of extensions safe and manageable, there is a strict set of
        governance applied to the definition and use of extensions. Though any
        implementer can define an extension, there is a set of requirements that SHALL
        be met as part of the definition of the extension. Applications processing a
        resource are required to check for modifier extensions.

        Modifier extensions SHALL NOT change the meaning of any elements on Resource
        or DomainResource (including cannot change the meaning of modifierExtension
        itself).
            :param dosage: Dosage for the medication for the specific guidelines.
            :param indicationCodeableConcept: None
            :param indicationReference: None
            :param patientCharacteristics: Characteristics of the patient that are relevant to the administration
        guidelines (for example, height, weight, gender, etc.).
        """
        super().__init__(
            id_=id_,
            extension=extension,
            modifierExtension=modifierExtension,
            dosage=dosage,
            indicationCodeableConcept=indicationCodeableConcept,
            indicationReference=indicationReference,
            patientCharacteristics=patientCharacteristics,
        )
