from __future__ import annotations
from typing import Optional, Union, List, Any, TYPE_CHECKING

from pyspark.sql.types import StructType, DataType
from spark_auto_mapper_fhir.fhir_types.boolean import FhirBoolean
from spark_auto_mapper_fhir.fhir_types.date import FhirDate
from spark_auto_mapper_fhir.fhir_types.date_time import FhirDateTime
from spark_auto_mapper_fhir.fhir_types.list import FhirList
from spark_auto_mapper_fhir.fhir_types.integer import FhirInteger
from spark_auto_mapper_fhir.fhir_types.string import FhirString
from spark_auto_mapper_fhir.complex_types.meta import Meta
from spark_auto_mapper_fhir.extensions.extension_base import ExtensionBase
from spark_auto_mapper_fhir.fhir_types.id import FhirId

from spark_auto_mapper_fhir.base_types.fhir_backbone_element_base import (
    FhirBackboneElementBase,
)

if TYPE_CHECKING:
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept
    # Import for CodeableConcept for type
    from spark_auto_mapper_fhir.value_sets.certainty_subcomponent_type import CertaintySubcomponentType
    # End Import for CodeableConcept for type
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept
    # Import for CodeableConcept for rating
    from spark_auto_mapper_fhir.value_sets.certainty_subcomponent_rating import CertaintySubcomponentRating
    # End Import for CodeableConcept for rating
    from spark_auto_mapper_fhir.complex_types.annotation import Annotation


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class RiskEvidenceSynthesisCertaintySubcomponent(FhirBackboneElementBase):
    """
    """
    # noinspection PyPep8Naming
    def __init__(
        self,
        *,
        id_: FhirId,
        extension: Optional[FhirList[ExtensionBase]] = None,
        type: Optional[CodeableConcept[CertaintySubcomponentType] ] = None,
        rating: Optional[FhirList[CodeableConcept[CertaintySubcomponentRating] ]] = None,
        note: Optional[FhirList[Annotation ]] = None,
    ) -> None:
        """

        :param id_: id of resource
        :param extension: extensions
        :param type: Type of subcomponent of certainty rating.
        :param rating: A rating of a subcomponent of rating certainty.
        :param note: A human-readable string to clarify or explain concepts about the resource.
        """
        super().__init__(
            id_=id_,
            extension=extension,
            type=type,
            rating=rating,
            note=note,
        )
