from __future__ import annotations
from typing import Optional, TYPE_CHECKING

from spark_auto_mapper_fhir.fhir_types.list import FhirList
from spark_auto_mapper_fhir.fhir_types.integer import FhirInteger
from spark_auto_mapper_fhir.fhir_types.string import FhirString

from spark_auto_mapper_fhir.base_types.fhir_backbone_element_base import (
    FhirBackboneElementBase,
)

if TYPE_CHECKING:
    pass
    # id_ (string)
    # extension (Extension)
    from spark_auto_mapper_fhir.extensions.extension import Extension

    # modifierExtension (Extension)
    # numberOfUnits (integer)
    # averageMolecularFormula (string)
    # repeatUnitAmountType (CodeableConcept)
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept

    # End Import for References for repeatUnitAmountType
    # Import for CodeableConcept for repeatUnitAmountType
    from spark_auto_mapper_fhir.value_sets.generic_type import GenericTypeCode

    # End Import for CodeableConcept for repeatUnitAmountType
    # repeatUnit (SubstancePolymer.RepeatUnit)
    from spark_auto_mapper_fhir.backbone_elements.substance_polymer_repeat_unit import (
        SubstancePolymerRepeatUnit,
    )


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class SubstancePolymerRepeat(FhirBackboneElementBase):
    """
    SubstancePolymer.Repeat
        Todo.
    """

    # noinspection PyPep8Naming
    def __init__(
        self,
        *,
        id_: Optional[FhirString] = None,
        extension: Optional[FhirList[Extension]] = None,
        modifierExtension: Optional[FhirList[Extension]] = None,
        numberOfUnits: Optional[FhirInteger] = None,
        averageMolecularFormula: Optional[FhirString] = None,
        repeatUnitAmountType: Optional[CodeableConcept[GenericTypeCode]] = None,
        repeatUnit: Optional[FhirList[SubstancePolymerRepeatUnit]] = None,
    ) -> None:
        """
            Todo.

            :param id_: None
            :param extension: May be used to represent additional information that is not part of the basic
        definition of the element. To make the use of extensions safe and manageable,
        there is a strict set of governance  applied to the definition and use of
        extensions. Though any implementer can define an extension, there is a set of
        requirements that SHALL be met as part of the definition of the extension.
            :param modifierExtension: May be used to represent additional information that is not part of the basic
        definition of the element and that modifies the understanding of the element
        in which it is contained and/or the understanding of the containing element's
        descendants. Usually modifier elements provide negation or qualification. To
        make the use of extensions safe and manageable, there is a strict set of
        governance applied to the definition and use of extensions. Though any
        implementer can define an extension, there is a set of requirements that SHALL
        be met as part of the definition of the extension. Applications processing a
        resource are required to check for modifier extensions.

        Modifier extensions SHALL NOT change the meaning of any elements on Resource
        or DomainResource (including cannot change the meaning of modifierExtension
        itself).
            :param numberOfUnits: Todo.
            :param averageMolecularFormula: Todo.
            :param repeatUnitAmountType: Todo.
            :param repeatUnit: Todo.
        """
        super().__init__(
            id_=id_,
            extension=extension,
            modifierExtension=modifierExtension,
            numberOfUnits=numberOfUnits,
            averageMolecularFormula=averageMolecularFormula,
            repeatUnitAmountType=repeatUnitAmountType,
            repeatUnit=repeatUnit,
        )
