from __future__ import annotations
from typing import Optional, Union, List, Any, TYPE_CHECKING

from pyspark.sql.types import StructType, DataType
from spark_auto_mapper_fhir.fhir_types.boolean import FhirBoolean
from spark_auto_mapper_fhir.fhir_types.date import FhirDate
from spark_auto_mapper_fhir.fhir_types.date_time import FhirDateTime
from spark_auto_mapper_fhir.fhir_types.list import FhirList
from spark_auto_mapper_fhir.fhir_types.integer import FhirInteger
from spark_auto_mapper_fhir.fhir_types.string import FhirString
from spark_auto_mapper_fhir.complex_types.meta import Meta
from spark_auto_mapper_fhir.extensions.extension_base import ExtensionBase
from spark_auto_mapper_fhir.fhir_types.id import FhirId

from spark_auto_mapper_fhir.base_types.fhir_backbone_element_base import (
    FhirBackboneElementBase,
)

if TYPE_CHECKING:
    # code (CodeableConcept)
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept
    # status (CodeableConcept)
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept
    # statusDate (dateTime)
    from spark_auto_mapper_fhir.complex_types.date_time import dateTime
    # comment (string)
    from spark_auto_mapper_fhir.complex_types.string import string
    # source (Reference)
    from spark_auto_mapper_fhir.complex_types.reference import Reference
    # Imports for References for source
    from spark_auto_mapper_fhir.resources.document_reference import DocumentReference


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class SubstanceSpecificationCode(FhirBackboneElementBase):
    """
    SubstanceSpecification.Code
    """
    # noinspection PyPep8Naming
    def __init__(
        self,
        *,
        id_: FhirId,
        extension: Optional[FhirList[ExtensionBase]] = None,
        code: Optional[CodeableConcept ] = None,
        status: Optional[CodeableConcept ] = None,
        statusDate: Optional[FhirDateTime ] = None,
        comment: Optional[FhirString ] = None,
        source: Optional[FhirList[Reference [Union[DocumentReference]]]] = None,
    ) -> None:
        """

        :param id_: id of resource
        :param extension: extensions
        :param code: The specific code.
        :param status: Status of the code assignment.
        :param statusDate: The date at which the code status is changed as part of the terminology
    maintenance.
        :param comment: Any comment can be provided in this field, if necessary.
        :param source: Supporting literature.
        """
        super().__init__(
            id_=id_,
            extension=extension,
            code=code,
            status=status,
            statusDate=statusDate,
            comment=comment,
            source=source,
        )
