from __future__ import annotations
from typing import Optional, TYPE_CHECKING, Union

# noinspection PyPackageRequirements
from pyspark.sql.types import StructType, DataType
from spark_auto_mapper_fhir.fhir_types.boolean import FhirBoolean
from spark_auto_mapper_fhir.fhir_types.list import FhirList
from spark_auto_mapper_fhir.complex_types.meta import Meta
from spark_auto_mapper_fhir.extensions.extension_base import ExtensionBase
from spark_auto_mapper_fhir.fhir_types.id import FhirId

from spark_auto_mapper_fhir.base_types.fhir_resource_base import FhirResourceBase
from spark_fhir_schemas.r4.resources.slot import SlotSchema

if TYPE_CHECKING:
    from spark_auto_mapper_fhir.complex_types.identifier import Identifier
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept

    # Import for CodeableConcept for serviceCategory
    from spark_auto_mapper_fhir.value_sets.servicecategory import Servicecategory

    # End Import for CodeableConcept for serviceCategory
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept

    # Import for CodeableConcept for serviceType
    from spark_auto_mapper_fhir.value_sets.servicetype import Servicetype

    # End Import for CodeableConcept for serviceType
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept
    from spark_auto_mapper_fhir.complex_types.codeable_concept import CodeableConcept
    from spark_auto_mapper_fhir.complex_types.reference import Reference

    # Imports for References for schedule
    from spark_auto_mapper_fhir.resources.schedule import Schedule
    from spark_auto_mapper_fhir.complex_types.slot_status import SlotStatus
    from spark_auto_mapper_fhir.complex_types.instant import instant
    from spark_auto_mapper_fhir.complex_types.instant import instant
    from spark_auto_mapper_fhir.complex_types.boolean import FhirBoolean
    from spark_auto_mapper_fhir.complex_types.string import FhirString


# This file is auto-generated by generate_classes so do not edit manually
# noinspection PyPep8Naming
class Slot(FhirResourceBase):
    """ """

    # noinspection PyPep8Naming
    def __init__(
        self,
        *,
        id_: FhirId,
        meta: Optional[Meta] = None,
        extension: Optional[FhirList[ExtensionBase]] = None,
        identifier: Optional[FhirList[Identifier]] = None,
        serviceCategory: Optional[FhirList[CodeableConcept[Servicecategory]]] = None,
        serviceType: Optional[FhirList[CodeableConcept[Servicetype]]] = None,
        specialty: Optional[FhirList[CodeableConcept]] = None,
        appointmentType: Optional[CodeableConcept] = None,
        schedule: Reference[Union[Schedule]],
        status: SlotStatus,
        start: instant,
        end: instant,
        overbooked: Optional[FhirBoolean] = None,
        comment: Optional[FhirString] = None,
    ) -> None:
        """

            :param id_: id of resource
            :param meta: Meta
            :param extension: extensions
            :param identifier: External Ids for this item.
            :param serviceCategory: A broad categorization of the service that is to be performed during this
        appointment.
            :param serviceType: The type of appointments that can be booked into this slot (ideally this would
        be an identifiable service - which is at a location, rather than the location
        itself). If provided then this overrides the value provided on the
        availability resource.
            :param specialty: The specialty of a practitioner that would be required to perform the service
        requested in this appointment.
            :param appointmentType: The style of appointment or patient that may be booked in the slot (not
        service type).
            :param schedule: The schedule resource that this slot defines an interval of status
        information.
            :param status: busy | free | busy-unavailable | busy-tentative | entered-in-error.
            :param start: Date/Time that the slot is to begin.
            :param end: Date/Time that the slot is to conclude.
            :param overbooked: This slot has already been overbooked, appointments are unlikely to be
        accepted for this time.
            :param comment: Comments on the slot to describe any extended information. Such as custom
        constraints on the slot.
        """
        super().__init__(
            resourceType="Slot",
            id_=id_,
            meta=meta,
            extension=extension,
            identifier=identifier,
            serviceCategory=serviceCategory,
            serviceType=serviceType,
            specialty=specialty,
            appointmentType=appointmentType,
            schedule=schedule,
            status=status,
            start=start,
            end=end,
            overbooked=overbooked,
            comment=comment,
        )

    def get_schema(
        self, include_extension: bool
    ) -> Optional[Union[StructType, DataType]]:
        return SlotSchema.get_schema(include_extension=include_extension)
